{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dfc\/idverificationerror\/apierror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/IDVerificationError\/apiError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is an actual error that has occured from an inner API."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"apiError","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:3DFC19IDVerificationErrorV03apiC0s0C0_pSgvp","modules":[{"name":"DFC"}]},"hierarchy":{"paths":[["doc:\/\/com.deserve.dfc\/documentation\/DFC","doc:\/\/com.deserve.dfc\/documentation\/DFC\/IDVerificationError"]]},"references":{"doc://com.deserve.dfc/documentation/DFC/IDVerificationError":{"role":"symbol","title":"IDVerificationError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDVerificationError"}],"abstract":[{"type":"text","text":"Class which holds information about error that may occur during IDVerification."}],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/IDVerificationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDVerificationError"}],"url":"\/documentation\/dfc\/idverificationerror"},"doc://com.deserve.dfc/documentation/DFC":{"role":"collection","title":"DFC","abstract":[],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC","kind":"symbol","type":"topic","url":"\/documentation\/dfc"},"doc://com.deserve.dfc/documentation/DFC/IDVerificationError/apiError":{"role":"symbol","title":"apiError","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This is an actual error that has occured from an inner API."}],"identifier":"doc:\/\/com.deserve.dfc\/documentation\/DFC\/IDVerificationError\/apiError","kind":"symbol","type":"topic","url":"\/documentation\/dfc\/idverificationerror\/apierror"}}}